- name: set hostname to hosts file
  lineinfile: >
    state=present
    dest=/etc/hosts
    line='{{ ipaddress | default('127.0.0.1') }} {{ item.servername }}'
    create=yes
  loop: "{{ apache_vhosts }}"

- name: restart network
  raw: /etc/init.d/networking restart
