- name: bootstrap
  connection: local
  hosts: vagrants
  gather_facts: no
  become: yes
  tasks:
    - name: set timezone to Asia/Tokyo
      timezone:
        name: Asia/Tokyo
    - name: add apt repository for php
      apt_repository:
        repo: ppa:ondrej/php
        update_cache: yes
    - name: apt update
      raw: apt update -qq
    - name: apt update and install items
      apt: name={{ item }} update_cache=yes cache_valid_time=3600
      with_items:
        - zip
        - unzip

- name: setup_lamp
  connection: local
  hosts: vagrants
  become: yes
  vars_files:
  - vars/local/mysql.yml
  - vars/local/apache.yml
  - vars/local/php.yml
  roles:
     - geerlingguy.php
     - geerlingguy.php-versions
     - geerlingguy.composer
     - geerlingguy.apache
     - geerlingguy.mysql

- name: setup_nvm
  connection: local
  hosts: vagrants
  gather_facts: no
  become: yes
  vars_files:
  - vars/local/nvm.yml
  roles:
    - moviedo.nvm

