- src: geerlingguy.php
  version: 3.7.0
- src: geerlingguy.php-versions
  version: 3.0.0
- src: geerlingguy.composer
  version: 1.7.3
- src: geerlingguy.mysql
  version: 2.9.4
- src: geerlingguy.apache
  version: 3.0.3
- src: moviedo.nvm
  version: v1.1.3
