- src: deluxebrain.ansible_role_nodejs
  version: master
- src: geerlingguy.apache
  version: 3.1.4
- src: geerlingguy.composer
  version: 1.9.0
- src: geerlingguy.mysql
  version: 3.3.0
- src: geerlingguy.php
  version: 4.5.1
- src: geerlingguy.php-versions
  version: 4.1.0
- src: geerlingguy.php-xdebug
  version: 3.0.0
- src: robertdebock.locale
  version: 2.4.6
